### ISSUE TITLE
Sign Up Error

### ISSUE THREAD

**Issue by Andrieddu** [vuestorefront/template-shopify#30]
Hello, 

I've found an issue in the Sign Up page, while I try to sign up a email that exist already instaed of giving me a "normal error" from Shopify such as "This email exist already" or something like that, it just give me a VSF error. 

[VSF][error]: useUser/register TypeError: Cannot read properties of undefined (reading 'customerUserErrors')

**Comment by aureate-labs-team** [comment]
Hello, this will requires composable and api level changes. We've resolved it and it will be resolved with the next release. Thanks for reporting.

**Comment by aureate-labs-team** [comment]
Resolved
